
[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=0E90CE864B13D753D57B2A96D5B9A827

[StartupActions]
bAddPacks=True
InsertPack=(PackSource="StarterContent.upack",PackName="StarterContent")

[SectionsToSave]
+Section=StartupActions

; GAS디버깅에서 플레이어 상태 업데이트 허용
[/Script/GameplayAbilities.AbilitySystemGlobals]
bUseDebugTargetFromHud=True